### ISSUE TITLE
A new type needed- genome_alignments 

### ISSUE THREAD

**Issue by sdash-github** [legumeinfo/datastore-registry#1]
We do not have genome_alignments type but we have started using it, e.g., in Aradu for aligning diploid genomes and using it in JB2. Will add it here in README after @cann0010 and/or @adf-ncgr concur.

> "Genus species type accession.type"   -- for example,  "Cicer arietinum genomes CDCFrontier.gnm3"
> The third field **should be one of the following types** :
> 
>   annotations genefamilies genomes maps markers methylation 
>   pangenes pangenomes repeats supplements synteny traits transcriptomes

**Comment by sammyjava** [comment]
@sdash-github I think you meant to post this under datastore-specifications. This repo is for storing KEY4 values, replacing the old spreadsheet on Google Drive.

**Comment by StevenCannon-USDA** [comment]
I think both @sdash-github and @sammyjava's comments pertain:

"genome_alignments" should be added to the README and the type-check in this registry repo;

... and a spec should be added over at datastore-specifications.

(I haven't followed this genome_alignments work closely, so I don't know what the specification should be. From my perspective, it just showed up.)

**Comment by adf-ncgr** [comment]
spec was already added:
https://github.com/legumeinfo/datastore-specifications/tree/main/Genus/species/genome_alignments
if I didn't send out an RFO, mea culpa

**Comment by StevenCannon-USDA** [comment]
Closing here, as I've added a check for "genome_alignments".
